name: Semgrep SAST

on:
  push:
    branches: [ "master", "main" ]

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --verbose
